# Generated by Django 2.2.3 on 2019-07-13 10:48

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_bizerte_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bizerte',
            name='rast',
            field=django.contrib.gis.db.models.fields.RasterField(default=3, srid=4326),
            preserve_default=False,
        ),
    ]
