# Generated by Django 2.2.3 on 2019-07-13 10:58

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_bizerte_rast'),
    ]

    operations = [
        migrations.AddField(
            model_name='bizerte',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='bizerte',
            name='line',
            field=django.contrib.gis.db.models.fields.LineStringField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='bizerte',
            name='mpoint',
            field=django.contrib.gis.db.models.fields.MultiPointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='bizerte',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='bizerte',
            name='rast',
            field=django.contrib.gis.db.models.fields.RasterField(null=True, srid=4326),
        ),
    ]
