# Generated by Django 2.2.3 on 2019-07-13 11:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0005_auto_20190713_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('rast', django.contrib.gis.db.models.fields.RasterField(null=True, srid=4326)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326)),
                ('point', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('line', django.contrib.gis.db.models.fields.LineStringField(null=True, srid=4326)),
                ('mpoint', django.contrib.gis.db.models.fields.MultiPointField(null=True, srid=4326)),
            ],
        ),
        migrations.RemoveField(
            model_name='bizerte',
            name='geom',
        ),
        migrations.RemoveField(
            model_name='bizerte',
            name='line',
        ),
        migrations.RemoveField(
            model_name='bizerte',
            name='mpoint',
        ),
        migrations.RemoveField(
            model_name='bizerte',
            name='point',
        ),
        migrations.RemoveField(
            model_name='bizerte',
            name='rast',
        ),
    ]
