# Generated by Django 2.2.3 on 2019-07-13 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0006_auto_20190713_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bizerte',
            name='image',
        ),
    ]
