# Generated by Django 2.2.3 on 2019-07-13 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0007_remove_bizerte_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bizerte',
        ),
    ]
