# Generated by Django 2.2.3 on 2019-07-13 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0009_remove_test_rast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='geom',
        ),
        migrations.RemoveField(
            model_name='test',
            name='line',
        ),
        migrations.RemoveField(
            model_name='test',
            name='point',
        ),
    ]
