# Generated by Django 2.2.3 on 2019-07-13 11:18

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0010_auto_20190713_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='mpoint',
        ),
        migrations.AddField(
            model_name='test',
            name='line',
            field=django.contrib.gis.db.models.fields.LineStringField(null=True, srid=4326),
        ),
    ]
