# Generated by Django 2.2.3 on 2019-07-13 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0011_auto_20190713_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='line',
        ),
    ]
