# Generated by Django 2.2.3 on 2019-07-13 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0012_remove_test_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='mpoly',
        ),
    ]
