# Generated by Django 2.2.3 on 2019-07-13 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0014_auto_20190713_1120'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test2',
        ),
    ]
